# Generated by Django 3.1 on 2020-10-21 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('pos_id', models.IntegerField(blank=True, null=True)),
                ('knowledge_of_service', models.IntegerField(blank=True, null=True)),
                ('knowledge_of_selling_products', models.IntegerField(blank=True, null=True)),
                ('have_scratch_card', models.IntegerField(blank=True, null=True)),
                ('have_evd', models.IntegerField(blank=True, null=True)),
                ('data_package', models.IntegerField(blank=True, null=True)),
                ('plug', models.IntegerField(blank=True, null=True)),
                ('x5', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('event_date', models.CharField(blank=True, max_length=50, null=True)),
                ('event_date_field', models.CharField(blank=True, db_column='event_date_', max_length=50, null=True)),
                ('distince_field', models.CharField(blank=True, db_column='distince_', max_length=50, null=True)),
                ('owner_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_telephone', models.IntegerField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('territory_id', models.IntegerField(blank=True, null=True)),
                ('knowledge_of_selling_products_field', models.CharField(blank=True, db_column='knowledge_of_selling_products_', max_length=50, null=True)),
                ('have_scratch_card_field', models.CharField(blank=True, db_column='have_scratch_card_', max_length=50, null=True)),
                ('have_evd_field', models.CharField(blank=True, db_column='have_evd_', max_length=50, null=True)),
                ('data_package_field', models.CharField(blank=True, db_column='data_package_', max_length=50, null=True)),
                ('plug_field', models.CharField(blank=True, db_column='plug_', max_length=50, null=True)),
                ('x5_field', models.CharField(blank=True, db_column='x5_', max_length=50, null=True)),
                ('user_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_telephone', models.IntegerField(blank=True, null=True)),
                ('agent_msisdn', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_momo', models.IntegerField(blank=True, null=True)),
                ('momo_amount', models.IntegerField(blank=True, null=True)),
                ('did_top_up_evd', models.IntegerField(blank=True, null=True)),
                ('evd_number', models.BigIntegerField(blank=True, null=True)),
                ('evd_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Training',
                'managed': True,
            },
        ),
    ]
