# Generated by Django 3.1 on 2020-11-21 19:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201029_2052'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='RegDist',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
        #         ('name', models.CharField(blank=True, db_column='Name', max_length=2000, null=True)),
        #         ('description', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('timestamp', models.DateTimeField(blank=True, null=True)),
        #         ('begin', models.DateTimeField(blank=True, null=True)),
        #         ('end', models.DateTimeField(blank=True, null=True)),
        #         ('altitudemode', models.CharField(blank=True, db_column='altitudeMode', max_length=2000, null=True)),
        #         ('tessellate', models.IntegerField(blank=True, null=True)),
        #         ('extrude', models.IntegerField(blank=True, null=True)),
        #         ('visibility', models.IntegerField(blank=True, null=True)),
        #         ('draworder', models.IntegerField(blank=True, db_column='drawOrder', null=True)),
        #         ('icon', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('descriptio', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('altitudemo', models.CharField(blank=True, db_column='altitudeMo', max_length=2000, null=True)),
        #         ('circuit_co', models.FloatField(blank=True, db_column='Circuit_Co', null=True)),
        #         ('pos_count', models.FloatField(blank=True, db_column='POS_Count', null=True)),
        #         ('shape_leng', models.FloatField(blank=True, db_column='Shape_Leng', null=True)),
        #         ('shape_area', models.FloatField(blank=True, db_column='Shape_Area', null=True)),
        #     ],
        #     options={
        #         'db_table': 'Reg_Dist',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Territories',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
        #         ('name', models.CharField(blank=True, db_column='Name', max_length=2000, null=True)),
        #         ('description', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('timestamp', models.DateTimeField(blank=True, null=True)),
        #         ('begin', models.DateTimeField(blank=True, null=True)),
        #         ('end', models.DateTimeField(blank=True, null=True)),
        #         ('altitudemode', models.CharField(blank=True, db_column='altitudeMode', max_length=2000, null=True)),
        #         ('tessellate', models.IntegerField(blank=True, null=True)),
        #         ('extrude', models.IntegerField(blank=True, null=True)),
        #         ('visibility', models.IntegerField(blank=True, null=True)),
        #         ('draworder', models.IntegerField(blank=True, db_column='drawOrder', null=True)),
        #         ('icon', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('source', models.CharField(blank=True, db_column='Source', max_length=2000, null=True)),
        #         ('descriptio', models.CharField(blank=True, max_length=2000, null=True)),
        #         ('altitudemo', models.CharField(blank=True, db_column='altitudeMo', max_length=2000, null=True)),
        #         ('county', models.CharField(blank=True, db_column='COUNTY', max_length=2000, null=True)),
        #         ('tsc_name', models.CharField(blank=True, db_column='TSC_Name', max_length=2000, null=True)),
        #         ('tsc_number', models.FloatField(blank=True, db_column='TSC_Number', null=True)),
        #         ('loc_rel', models.CharField(blank=True, db_column='Loc_Rel', max_length=2000, null=True)),
        #         ('pos_count', models.FloatField(blank=True, db_column='POS_Count', null=True)),
        #         ('circuit_co', models.FloatField(blank=True, db_column='Circuit_Co', null=True)),
        #         ('cell_count', models.FloatField(blank=True, db_column='Cell_Count', null=True)),
        #     ],
        #     options={
        #         'db_table': 'territories',
        #         'managed': False,
        #     },
        # ),
        # migrations.AlterModelTable(
        #     name='training4326',
        #     table='tbl_training',
        # ),
    ]
