# Generated by Django 2.2.4 on 2019-08-31 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_da', models.CharField(blank=True, max_length=254, null=True)),
                ('delete_fie', models.CharField(blank=True, max_length=10, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('north', models.CharField(blank=True, max_length=15, null=True)),
                ('west', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'forestry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('reserve_na', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Protected Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalBoundary2019',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Regional_Boundary_2019',
                'managed': False,
            },
        ),
    ]
